version: "3.3"
services:
        db:
                image: mysql
                container_name: db_docker_symfony
                restart: always
                volumes:
                    - ./data:/var/lib/mysql
                environment:
                    MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
                ports:
                    - 3306:3306
                networks:
                    - dev
        phpmyadmin:
                image: phpmyadmin
                container_name: phpmyadmin_docker_symfony
                restart: always
                depends_on:
                        - db
                ports:
                        - 8080:80
                environment:
                        PMA_HOST: db
                networks:
                        - dev
        maildev:
                image: maildev/maildev
                container_name: maildev_docker_symfony
                command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
                ports:
                        - "8081:80"
                restart: always
                networks:
                        - dev
volumes:
        db-data:
networks:
        dev:
